
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<h1 class="text-center my-3">LogIn</h1>


<form method="post" action="/login" id="loginForm">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="pass" class="form-control" name="pass" placeholder="Password">
  </div>
    
  <button type="submit" class="btn btn-primary" id="loginBtn">Submit</button>
</form>


<script src="./../../../public/js/login.js" type="text/javascript">
</script>