
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>



<h1 class="text-center my-3">Register</h1>


<form method="post" action="/register" id="userForm">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Full Name</label>
      <input type="text" class="form-control" name="fName" placeholder="Enter Your Full Name">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Email</label>
      <input type="email" class="form-control" name="email" placeholder="Enter Your Email Address">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Password</label>
    <input type="password" class="form-control" name="pass" placeholder="Enter Your Password">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Confirm Password</label>
    <input type="password" class="form-control" name="confirmPass" placeholder="Confirm Your Password">
  </div>
  <div class="form-group">
    <label for="inputAddress2">Mobile Number</label>
    <input type="number" class="form-control" name="mobileNumber" placeholder="Enter Your Mobile Number">
  </div>
 
  <button type="submit" class="btn btn-primary" id="addUserBtn">Sign in</button>
</form>


<!-- JavaScript -->
<script src="./../../../public/js/register.js" type="text/javascript">
</script>