<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?= $this->headTitle('HM')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <style>
        /* body {
            padding-top: 70px;
        } */

        .app {
            min-height: 100vh;
        }

        .app-footer {
            padding-bottom: 1em;
        }

        /* .mezzio-green,
        h2 a,
        h2 a:hover {
            color: #009655;
        }

        .navbar-brand {
            padding: 0;
        }

        .navbar-brand img {
            margin: -.5rem 0;
            filter: brightness(0) invert(1);
        } */
    </style>
</head>

<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">HM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('about') ?>">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('register') ?>">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $this->url('login') ?>">LogIn</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?= $this->content ?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; <?= date('Y') ?> <a href="https://getlaminas.org/">HM</a> a Series of LF Projects, LLC.
            </p>
        </div>
    </footer>

    <?= $this->inlineScript() ?>
</body>

</html>